jobs:
  dependabot:
    env:
      GITHUB_TOKEN: ${{secrets.SYNCED_GITHUB_TOKEN_REPO}}
      PR_URL: ${{github.event.pull_request.html_url}}
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: approve
      run: gh pr review --approve "$PR_URL"
    - continue-on-error: true
      name: merge
      run: gh pr merge --auto --squash --delete-branch "$PR_URL"
  test:
    uses: ./.github/workflows/test.yml
name: Dependabot
on:
  repository_dispatch:
    types: trigger-ga___dependabot.yml
permissions:
  contents: write
