jobs:
  gh-page-sync:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Generate documentation
      run: './gradlew dokkaHtml


        echo "Creating tar for generated docs"

        cd $GITHUB_WORKSPACE/library/build/dokka/html && tar cvf ~/android-maps-utils-docs.tar
        .


        echo "Unpacking tar into gh-pages branch"

        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

        cd $GITHUB_WORKSPACE && git checkout gh-pages && tar xvf ~/android-maps-utils-docs.tar

        '
    - continue-on-error: true
      name: PR Changes
      uses: peter-evans/create-pull-request@v3
      with:
        author: googlemaps-bot <googlemaps-bot@google.com>
        body: 'Updated GitHub pages with latest from `./gradlew dokkaHtml`.

          '
        branch: googlemaps-bot/update_gh_pages
        commit-message: 'docs: Update docs'
        committer: googlemaps-bot <googlemaps-bot@google.com>
        labels: docs
        title: 'docs: Update docs'
        token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
name: Update documentation
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
