jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.1.0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build modules
      run: ./gradlew build jacocoTestReport --stacktrace
name: Run unit tests
on:
  repository_dispatch:
    types: trigger-ga___test.yml
